# Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/flightSearch
spring.datasource.username=root
spring.datasource.password=rootpassword

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# App properties
FlightSearch.app.jwtCookieName=FlightSearch-Token
FlightSearch.app.jwtSecret=SecretPassword
FlightSearch.app.jwtExpirationMs=3600000

#Swagger properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# application.properties
aviationstack.api.url=http://api.aviationstack.com/v1

#aviationstack.api.key=KLUCZ_DO_API