spring.datasource.url=jdbc:mysql://localhost:3306/flightSearch
spring.datasource.username=root
spring.datasource.password=rootpassword

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# App properties
FlightSearch.app.jwtCookieName=FlightSearch-Token
FlightSearch.app.jwtSecret=SecretPassword
FlightSearch.app.jwtExpirationMs=3600000
